export const PUB_SUB = 'PUB_SUB';
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const UPDATE_ORDER_LIST = 'UPDATE_ORDER_LIST';
export const UPDATE_DRIVER_LOCATION = 'UPDATE_DRIVER_LOCATION';
export const ORDER_CALL_STATUS = 'ORDER_CALL_STATUS';
export const NEW_CHAT = 'NEW_CHAT';
